# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
import torch

random_tensor = torch.rand(size=(7, 7))
random_tensor

tensor([[0.0696, 0.7525, 0.3747, 0.8116, 0.5286, 0.1208, 0.1359],
        [0.6278, 0.1732, 0.3518, 0.1095, 0.8861, 0.9088, 0.7493],
        [0.8620, 0.1908, 0.5122, 0.9371, 0.6409, 0.0853, 0.0721],
        [0.5409, 0.0220, 0.7396, 0.7935, 0.9876, 0.6746, 0.4872],
        [0.0875, 0.4030, 0.7998, 0.7361, 0.0122, 0.6600, 0.4127],
        [0.2892, 0.0142, 0.0476, 0.6334, 0.1092, 0.7529, 0.8266],
        [0.1618, 0.2397, 0.0879, 0.5083, 0.2320, 0.1497, 0.7110]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
rand_tensor = torch.rand(size=(1, 7))

result = torch.mm(random_tensor, rand_tensor.T)
result

tensor([[1.1129],
        [2.2274],
        [1.7249],
        [2.1200],
        [1.2048],
        [1.2881],
        [0.9269]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [17]:
import torch

torch.manual_seed(0)

random_tensor = torch.rand(size=(7, 7))
rand_tensor = torch.rand(size=(1, 7))

result = torch.mm(random_tensor, rand_tensor.T)
result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
torch.cuda.manual_seed(1234)

tensor = torch.tensor(
    [2, 3],
    device="cuda",
)
tensor.device


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_a = torch.rand(size=(2, 3), device=device)
tensor_b = torch.rand(size=(2, 3), device=device)

print(f"Device: {device}")
print(tensor_a, tensor_b)


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
result = torch.mm(tensor_a, tensor_b.T)
result, result.shape

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
torch.max(result), torch.min(result)

### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
print(result.argmax())
print(result.argmin())


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
torch.manual_seed(7)
rand_tensor = torch.rand(size=(1, 1, 1, 10))

torch.manual_seed(7)
x = torch.rand(size=(1, 1, 1, 10))
x, x.shape

x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape